INSERT INTO colles (name, uni, color, img_path)
VALUES
('Al·lots de Llevant', false, null, null),
('Angelets del Vallespir', false, null, null),
('Bordegassos de Vilanova', false, null, null),
('Brivalls de Cornudella', false, null, null),
('Capgrossos de Mataró', false, null, null),
('Castellers d\'Altafulla', false, null, null),
('Castellers d\'Andorra', false, null, null),
('Castellers d\'Esparreguera', false, null, null),
('Castellers d\'Esplugues', false, null, null),
('Castellers de Badalona', false, null, null),
('Castellers de Barcelona', false, null, null),
('Castellers de Berga', false, null, null),
('Castellers de Caldes de Montbui', false, null, null),
('Castellers de Castellar del Vallès', false, null, null),
('Castellers de Castelldefels', false, null, null),
('Castellers de Cerdanyola', false, null, null),
('Castellers de Cornellà', false, null, null),
('Castellers de Gavà', false, null, null),
('Castellers de l\'Alt Maresme', false, null, null),
('Castellers de la Sagrada Família', false, null, null),
('Castellers de la Vila de Gràcia', false, null, null),
('Castellers de les Roquetes', false, null, null),
('Castellers de Lleida', false, null, null),
('Castellers de Mallorca', false, null, null),
('Castellers de Mollet', false, null, null),
('Castellers de Montcada i Reixac', false, null, null),
('Castellers de Rubí', false, null, null),
('Castellers de Sabadell', false, null, null),
('Castellers de Sant Adrià', false, null, null),
('Castellers de Sant Cugat', false, null, null),
('Castellers de Sant Feliu', false, null, null),
('Castellers de Sant Pere i Sant Pau', false, null, null),
('Castellers de Sant Vicenç dels Horts', false, null, null),
('Castellers de Santa Coloma', false, null, null),
('Castellers de Santpedor', false, null, null),
('Castellers de Sants', false, null, null),
('Castellers de Solsona', false, null, null),
('Castellers de Terrassa', false, null, null),
('Castellers de Viladecans', false, null, null),
('Castellers de Vilafranca', false, null, null),
('Castellers del Poble Sec', false, null, null),
('Castellers del Prat de Llobregat', false, null, null),
('Castellers del Riberal', false, null, null),
('Colla Castellera de Figueres', false, null, null),
('Colla Castellera de la Gavarresa', false, null, null),
('Xoriguers de la UDG', false, null, null),
('Penjats del Campus de Manresa', true, null, null),
('Pataquers de la URV', true, null, null),
('Passerells del TCM', true, null, null),
('Llunàtics UPC Vilanova', true, null, null),
('Grillats del Campus del Baix Llobregat', true, null, null),
('Ganàpies de la UAB', true, null, null),
('Engrescats de URL', true, null, null),
('Emboirats de la Universitat de Vic', true, null, null),
('Bergants del Campus de Terrassa' , true, null, null),
('Arreplegats de la Zona Universitària' , true, null, null),
('Xiquets del Serrallo' , false, null, null),
('Xiquets de Tarragona' , false, null, null),
('Xiquets de Vila-seca' , false, null, null),
('Xiquets de Reus' , false, null, null),
('Xiquets de Cambrils' , false, null, null),
('Xiquets de Reus' , false, null, null),
('Xiquets d\'Alcover' , false, null, null),
('Xiqüelos i Xiqüeles del Delta' , false, null, null),
('Xics de Granollers' , false, null, null),
('Xics Caleros' , false, null, null),
('Xicots de Vilafranca' , false, null, null),
('Xerrics d\'Olot' , false, null, null),
('Vailets de l\'Empordà' , false, null, null),
('Vailets de Gelida' , false, null, null),
('Torraires de Montblanc', false, null, null),
('Salats de Súria', false, null, null),
('Sagals d\'Osona' , false, null, null),
('Pallagos del Conflent' , false, null, null),
('Nois de la Torre' , false, null, null),
('Nens del Vendrell' , false, null, null),
('Moixiganguers d\'Igualada' , false, null, null),
('Minyons de Terrassa' , false, null, null),
('Minyons de Santa Cristina d\'Aro' , false, null, null),
('Minyons de l\'Arboç' , false, null, null),
('Minyons de Santa Cristina d\'Aro' , false, null, null),
('Matossers de Molins de Rei' , false, null, null),
('Marrecs de Salt' , false, null, null),
('Margeners de Guissona' , false, null, null),
('Laietans de Gramenet' , false, null, null),
('Esperxats de l\'Estany' , false, null, null),
('Encantats de Begues' , false, null, null),
('Colla Vella dels Xiquets de Valls' , false, null, null),
('Colla Joves Xiquets de Valls' , false, null, null),
('Colla Jove Xiquets de Vilafranca' , false, null, null),
('Colla Jove Xiquets de Tarragona' , false, null, null),
('Colla Jove de l\'Hospitalet' , false, null, null),
('Colla Jove de Castellers de Sitges' , false, null, null),
('Colla Castellera Nyerros de la Plana' , false, null, null),
('Colla Castellera Jove de Barcelona' , false, null, null);